name = "blogapp"
main = "src/index.ts"
compatibility_date = "2024-08-07"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOWMzYWMxOTAtNmU1OC00MDE1LTlmMTEtMzZjNDgyOTRiOWIxIiwidGVuYW50X2lkIjoiYTRjZTE3Y2UyMDMwY2E3N2VkZTFhZGFiNjZhMjE0ZmI5NGY1ZjczODdmOTdkNzIyODUwMzAxMTQyNGJlOTQ3MyIsImludGVybmFsX3NlY3JldCI6IjZjMDhmMzlkLWMzOGUtNGNhYi05N2Q2LTMxNzMyM2U3YzdkMSJ9.w6U5comTxlKKdXh2t7_6kDNN6s8M_T16lStzNi795GY"
DATABASE_URL_MIGRATE="postgresql://test_owner:N6TKDQEdLq3J@ep-wispy-wind-a1p80umy.ap-southeast-1.aws.neon.tech/blogAppStaging?sslmode=require"
JWT_SECRET="my_secret_pass"

UPSTASH_REDIS_REST_URL="https://prime-pegasus-14897.upstash.io"
UPSTASH_REDIS_REST_TOKEN="AToxAAIjcDE4MWUyNjZiOGY5M2E0MjU1OTc3NTFlZGZjOGE5OGJlMHAxMA"

RAILWAY_CONSUMER_WAKEUP_URL="https://blog-app-production-e887.up.railway.app/wakeup"
RAILWAY_WAKEUP_SECRET="zjkiY5vxEpBk+owJ48s62dhH9PUvhrH37U2pZmX9LbI="

UPSTASH_RATELIMIT_REDIS_REST_URL="https://crucial-slug-57112.upstash.io"
UPSTASH_RATELIMIT_REDIS_REST_TOKEN="Ad8YAAIjcDFhYmU3ZmE5ZTI4MmM0NmQ0ODViMDE3NDc5OTljMWY4MXAxMA"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
