package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/kunalPisolkar24/topos/services/content/graph/model"
	"github.com/kunalPisolkar24/topos/services/content/internal/domain"
	"github.com/kunalPisolkar24/topos/services/content/internal/middleware"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	userID, ok := middleware.UserIDFromContext(ctx)
	if !ok {
		return nil, mapDomainError(domain.ErrUnauthorized)
	}

	var tags []string
	if input.Tags != nil {
		tags = append(tags, input.Tags...)
	}

	post, err := r.PostService.CreatePost(ctx, input.Title, input.Body, userID, tags, input.ImageURL, input.Summary)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapDomainPostToModel(post), nil
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, id string, input model.UpdatePostInput) (*model.Post, error) {
	userID, ok := middleware.UserIDFromContext(ctx)
	if !ok {
		return nil, mapDomainError(domain.ErrUnauthorized)
	}

	var tags []string
	if input.Tags != nil {
		tags = append(tags, input.Tags...)
	}

	post, err := r.PostService.UpdatePost(ctx, id, userID, input.Title, input.Body, tags, input.ImageURL)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapDomainPostToModel(post), nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (bool, error) {
	userID, ok := middleware.UserIDFromContext(ctx)
	if !ok {
		return false, mapDomainError(domain.ErrUnauthorized)
	}

	if err := r.PostService.DeletePost(ctx, id, userID); err != nil {
		return false, mapDomainError(err)
	}
	return true, nil
}

// GenerateTags is the resolver for the generateTags field.
func (r *mutationResolver) GenerateTags(ctx context.Context, title string, body string) ([]string, error) {
	return r.PostService.GenerateTags(ctx, title, body)
}

// GeneratePostContent is the resolver for the generatePostContent field.
func (r *mutationResolver) GeneratePostContent(ctx context.Context, prompt string) (*model.GeneratedPost, error) {
	post, err := r.PostService.GeneratePostContent(ctx, prompt)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapDomainGeneratedPostToModel(post), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, page *int, limit *int) (*model.PaginatedPosts, error) {
	posts, err := r.PostService.GetPosts(ctx, deref(page), deref(limit))
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapDomainPaginatedToModel(posts), nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	post, err := r.PostService.GetPost(ctx, id)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapDomainPostToModel(post), nil
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context, query *string, limit *int) ([]*model.Tag, error) {
	tags, err := r.TagService.GetTags(ctx, query, deref(limit))
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapDomainTagsToModel(tags), nil
}

// PostsByTag is the resolver for the postsByTag field.
func (r *queryResolver) PostsByTag(ctx context.Context, tag string, page *int, limit *int) (*model.PaginatedPosts, error) {
	posts, err := r.PostService.GetPostsByTag(ctx, tag, deref(page), deref(limit))
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapDomainPaginatedToModel(posts), nil
}

// Posts is the resolver for the posts field.
func (r *userResolver) Posts(ctx context.Context, obj *model.User, page *int, limit *int) (*model.PaginatedPosts, error) {
	posts, err := r.PostService.GetPostsByAuthor(ctx, obj.ID, deref(page), deref(limit))
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapDomainPaginatedToModel(posts), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

func deref(v *int) int {
	if v == nil {
		return 0
	}
	return *v
}

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
