// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Chat struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type ChatMessage struct {
	ID           string      `json:"id"`
	ChatID       string      `json:"chatId"`
	Role         MessageRole `json:"role"`
	Content      string      `json:"content"`
	CitedPostIds []string    `json:"citedPostIds"`
	CreatedAt    string      `json:"createdAt"`
}

type CreatePostInput struct {
	Title    string   `json:"title"`
	Body     string   `json:"body"`
	Summary  *string  `json:"summary,omitempty"`
	Tags     []string `json:"tags,omitempty"`
	ImageURL *string  `json:"imageUrl,omitempty"`
}

type GeneratedPost struct {
	Title   string   `json:"title"`
	Body    string   `json:"body"`
	Summary string   `json:"summary"`
	Tags    []string `json:"tags"`
}

type Mutation struct {
}

type PaginatedMessages struct {
	Messages      []*ChatMessage `json:"messages"`
	TotalPages    int            `json:"totalPages"`
	CurrentPage   int            `json:"currentPage"`
	TotalMessages int            `json:"totalMessages"`
}

type PaginatedPosts struct {
	Posts       []*Post `json:"posts"`
	TotalPages  int     `json:"totalPages"`
	CurrentPage int     `json:"currentPage"`
	TotalPosts  int     `json:"totalPosts"`
}

type Post struct {
	ID            string         `json:"id"`
	Title         string         `json:"title"`
	Body          string         `json:"body"`
	Slug          string         `json:"slug"`
	ImageURL      *string        `json:"imageUrl,omitempty"`
	Summary       *string        `json:"summary,omitempty"`
	SummaryStatus *SummaryStatus `json:"summaryStatus,omitempty"`
	Author        *User          `json:"author"`
	Tags          []*Tag         `json:"tags"`
	CreatedAt     string         `json:"createdAt"`
	UpdatedAt     string         `json:"updatedAt"`
	Related       []*Post        `json:"related"`
}

func (Post) IsEntity() {}

type Query struct {
}

type SearchResult struct {
	Hits  []*Post `json:"hits"`
	Total int     `json:"total"`
}

type Tag struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UpdatePostInput struct {
	Title    *string  `json:"title,omitempty"`
	Body     *string  `json:"body,omitempty"`
	Tags     []string `json:"tags,omitempty"`
	ImageURL *string  `json:"imageUrl,omitempty"`
}

type User struct {
	ID    string          `json:"id"`
	Posts *PaginatedPosts `json:"posts"`
}

func (User) IsEntity() {}

type MessageRole string

const (
	MessageRoleUser      MessageRole = "USER"
	MessageRoleAssistant MessageRole = "ASSISTANT"
)

var AllMessageRole = []MessageRole{
	MessageRoleUser,
	MessageRoleAssistant,
}

func (e MessageRole) IsValid() bool {
	switch e {
	case MessageRoleUser, MessageRoleAssistant:
		return true
	}
	return false
}

func (e MessageRole) String() string {
	return string(e)
}

func (e *MessageRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MessageRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MessageRole", str)
	}
	return nil
}

func (e MessageRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MessageRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MessageRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SummaryStatus string

const (
	SummaryStatusPending   SummaryStatus = "PENDING"
	SummaryStatusCompleted SummaryStatus = "COMPLETED"
	SummaryStatusFailed    SummaryStatus = "FAILED"
)

var AllSummaryStatus = []SummaryStatus{
	SummaryStatusPending,
	SummaryStatusCompleted,
	SummaryStatusFailed,
}

func (e SummaryStatus) IsValid() bool {
	switch e {
	case SummaryStatusPending, SummaryStatusCompleted, SummaryStatusFailed:
		return true
	}
	return false
}

func (e SummaryStatus) String() string {
	return string(e)
}

func (e *SummaryStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SummaryStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SummaryStatus", str)
	}
	return nil
}

func (e SummaryStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SummaryStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SummaryStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
