// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/ai/ai_service.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentRequest) Reset() {
	*x = ContentRequest{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentRequest) ProtoMessage() {}

func (x *ContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentRequest.ProtoReflect.Descriptor instead.
func (*ContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *ContentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentResponse) Reset() {
	*x = ContentResponse{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentResponse) ProtoMessage() {}

func (x *ContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentResponse.ProtoReflect.Descriptor instead.
func (*ContentResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *ContentResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextRequest) Reset() {
	*x = ContextRequest{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextRequest) ProtoMessage() {}

func (x *ContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextRequest.ProtoReflect.Descriptor instead.
func (*ContextRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{2}
}

func (x *ContextRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContextRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type TagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagsResponse) Reset() {
	*x = TagsResponse{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsResponse) ProtoMessage() {}

func (x *TagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsResponse.ProtoReflect.Descriptor instead.
func (*TagsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{3}
}

func (x *TagsResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type PostGenerationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostGenerationRequest) Reset() {
	*x = PostGenerationRequest{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostGenerationRequest) ProtoMessage() {}

func (x *PostGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostGenerationRequest.ProtoReflect.Descriptor instead.
func (*PostGenerationRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{4}
}

func (x *PostGenerationRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type PostGenerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostGenerationResponse) Reset() {
	*x = PostGenerationResponse{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostGenerationResponse) ProtoMessage() {}

func (x *PostGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostGenerationResponse.ProtoReflect.Descriptor instead.
func (*PostGenerationResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{5}
}

func (x *PostGenerationResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostGenerationResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *PostGenerationResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PostGenerationResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type IndexRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	PostId  string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Title   string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body    string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Summary string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Tags    []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	// created_at is the post's creation time, UTC. It is carried as a
	// typed timestamp so consumers never have to guess a string format.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRequest) Reset() {
	*x = IndexRequest{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRequest) ProtoMessage() {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRequest.ProtoReflect.Descriptor instead.
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{6}
}

func (x *IndexRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *IndexRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *IndexRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *IndexRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *IndexRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *IndexRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type IndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexResponse) Reset() {
	*x = IndexResponse{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexResponse) ProtoMessage() {}

func (x *IndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexResponse.ProtoReflect.Descriptor instead.
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{7}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{9}
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{10}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostIds       []string               `protobuf:"bytes,1,rep,name=post_ids,json=postIds,proto3" json:"post_ids,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{11}
}

func (x *SearchResponse) GetPostIds() []string {
	if x != nil {
		return x.PostIds
	}
	return nil
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RelatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelatedRequest) Reset() {
	*x = RelatedRequest{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelatedRequest) ProtoMessage() {}

func (x *RelatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelatedRequest.ProtoReflect.Descriptor instead.
func (*RelatedRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{12}
}

func (x *RelatedRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *RelatedRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RelatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostIds       []string               `protobuf:"bytes,1,rep,name=post_ids,json=postIds,proto3" json:"post_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelatedResponse) Reset() {
	*x = RelatedResponse{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelatedResponse) ProtoMessage() {}

func (x *RelatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelatedResponse.ProtoReflect.Descriptor instead.
func (*RelatedResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{13}
}

func (x *RelatedResponse) GetPostIds() []string {
	if x != nil {
		return x.PostIds
	}
	return nil
}

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{14}
}

func (x *EmbedRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{15}
}

func (x *EmbedResponse) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{16}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	History       []*ChatMessage         `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`
	TopK          uint32                 `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatAnswerRequest) Reset() {
	*x = ChatAnswerRequest{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatAnswerRequest) ProtoMessage() {}

func (x *ChatAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatAnswerRequest.ProtoReflect.Descriptor instead.
func (*ChatAnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{17}
}

func (x *ChatAnswerRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ChatAnswerRequest) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *ChatAnswerRequest) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type ChatChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	CitedPostIds  []string               `protobuf:"bytes,3,rep,name=cited_post_ids,json=citedPostIds,proto3" json:"cited_post_ids,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatChunk) Reset() {
	*x = ChatChunk{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatChunk) ProtoMessage() {}

func (x *ChatChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatChunk.ProtoReflect.Descriptor instead.
func (*ChatChunk) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{18}
}

func (x *ChatChunk) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *ChatChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ChatChunk) GetCitedPostIds() []string {
	if x != nil {
		return x.CitedPostIds
	}
	return nil
}

func (x *ChatChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_ai_ai_service_proto protoreflect.FileDescriptor

const file_proto_ai_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/ai/ai_service.proto\x12\x02ai\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n" +
	"\x0eContentRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"+\n" +
	"\x0fContentResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\":\n" +
	"\x0eContextRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"\"\n" +
	"\fTagsResponse\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\"/\n" +
	"\x15PostGenerationRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"p\n" +
	"\x16PostGenerationResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"\xba\x01\n" +
	"\fIndexRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x0f\n" +
	"\rIndexResponse\"(\n" +
	"\rDeleteRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"\x10\n" +
	"\x0eDeleteResponse\"S\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"A\n" +
	"\x0eSearchResponse\x12\x19\n" +
	"\bpost_ids\x18\x01 \x03(\tR\apostIds\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"?\n" +
	"\x0eRelatedRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\",\n" +
	"\x0fRelatedResponse\x12\x19\n" +
	"\bpost_ids\x18\x01 \x03(\tR\apostIds\"\"\n" +
	"\fEmbedRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"'\n" +
	"\rEmbedResponse\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"i\n" +
	"\x11ChatAnswerRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12)\n" +
	"\ahistory\x18\x02 \x03(\v2\x0f.ai.ChatMessageR\ahistory\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\rR\x04topK\"q\n" +
	"\tChatChunk\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12$\n" +
	"\x0ecited_post_ids\x18\x03 \x03(\tR\fcitedPostIds\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\xfe\x03\n" +
	"\tAIService\x12:\n" +
	"\x0fGenerateSummary\x12\x12.ai.ContentRequest\x1a\x13.ai.ContentResponse\x124\n" +
	"\fGenerateTags\x12\x12.ai.ContextRequest\x1a\x10.ai.TagsResponse\x12E\n" +
	"\fGeneratePost\x12\x19.ai.PostGenerationRequest\x1a\x1a.ai.PostGenerationResponse\x120\n" +
	"\tIndexPost\x12\x10.ai.IndexRequest\x1a\x11.ai.IndexResponse\x123\n" +
	"\n" +
	"DeletePost\x12\x11.ai.DeleteRequest\x1a\x12.ai.DeleteResponse\x124\n" +
	"\vSearchPosts\x12\x11.ai.SearchRequest\x1a\x12.ai.SearchResponse\x127\n" +
	"\fRelatedPosts\x12\x12.ai.RelatedRequest\x1a\x13.ai.RelatedResponse\x12,\n" +
	"\x05Embed\x12\x10.ai.EmbedRequest\x1a\x11.ai.EmbedResponse\x124\n" +
	"\n" +
	"ChatAnswer\x12\x15.ai.ChatAnswerRequest\x1a\r.ai.ChatChunk0\x01B<Z:github.com/kunalPisolkar24/topos/services/content/proto/aib\x06proto3"

var (
	file_proto_ai_ai_service_proto_rawDescOnce sync.Once
	file_proto_ai_ai_service_proto_rawDescData []byte
)

func file_proto_ai_ai_service_proto_rawDescGZIP() []byte {
	file_proto_ai_ai_service_proto_rawDescOnce.Do(func() {
		file_proto_ai_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_ai_service_proto_rawDesc), len(file_proto_ai_ai_service_proto_rawDesc)))
	})
	return file_proto_ai_ai_service_proto_rawDescData
}

var file_proto_ai_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_ai_ai_service_proto_goTypes = []any{
	(*ContentRequest)(nil),         // 0: ai.ContentRequest
	(*ContentResponse)(nil),        // 1: ai.ContentResponse
	(*ContextRequest)(nil),         // 2: ai.ContextRequest
	(*TagsResponse)(nil),           // 3: ai.TagsResponse
	(*PostGenerationRequest)(nil),  // 4: ai.PostGenerationRequest
	(*PostGenerationResponse)(nil), // 5: ai.PostGenerationResponse
	(*IndexRequest)(nil),           // 6: ai.IndexRequest
	(*IndexResponse)(nil),          // 7: ai.IndexResponse
	(*DeleteRequest)(nil),          // 8: ai.DeleteRequest
	(*DeleteResponse)(nil),         // 9: ai.DeleteResponse
	(*SearchRequest)(nil),          // 10: ai.SearchRequest
	(*SearchResponse)(nil),         // 11: ai.SearchResponse
	(*RelatedRequest)(nil),         // 12: ai.RelatedRequest
	(*RelatedResponse)(nil),        // 13: ai.RelatedResponse
	(*EmbedRequest)(nil),           // 14: ai.EmbedRequest
	(*EmbedResponse)(nil),          // 15: ai.EmbedResponse
	(*ChatMessage)(nil),            // 16: ai.ChatMessage
	(*ChatAnswerRequest)(nil),      // 17: ai.ChatAnswerRequest
	(*ChatChunk)(nil),              // 18: ai.ChatChunk
	(*timestamppb.Timestamp)(nil),  // 19: google.protobuf.Timestamp
}
var file_proto_ai_ai_service_proto_depIdxs = []int32{
	19, // 0: ai.IndexRequest.created_at:type_name -> google.protobuf.Timestamp
	16, // 1: ai.ChatAnswerRequest.history:type_name -> ai.ChatMessage
	0,  // 2: ai.AIService.GenerateSummary:input_type -> ai.ContentRequest
	2,  // 3: ai.AIService.GenerateTags:input_type -> ai.ContextRequest
	4,  // 4: ai.AIService.GeneratePost:input_type -> ai.PostGenerationRequest
	6,  // 5: ai.AIService.IndexPost:input_type -> ai.IndexRequest
	8,  // 6: ai.AIService.DeletePost:input_type -> ai.DeleteRequest
	10, // 7: ai.AIService.SearchPosts:input_type -> ai.SearchRequest
	12, // 8: ai.AIService.RelatedPosts:input_type -> ai.RelatedRequest
	14, // 9: ai.AIService.Embed:input_type -> ai.EmbedRequest
	17, // 10: ai.AIService.ChatAnswer:input_type -> ai.ChatAnswerRequest
	1,  // 11: ai.AIService.GenerateSummary:output_type -> ai.ContentResponse
	3,  // 12: ai.AIService.GenerateTags:output_type -> ai.TagsResponse
	5,  // 13: ai.AIService.GeneratePost:output_type -> ai.PostGenerationResponse
	7,  // 14: ai.AIService.IndexPost:output_type -> ai.IndexResponse
	9,  // 15: ai.AIService.DeletePost:output_type -> ai.DeleteResponse
	11, // 16: ai.AIService.SearchPosts:output_type -> ai.SearchResponse
	13, // 17: ai.AIService.RelatedPosts:output_type -> ai.RelatedResponse
	15, // 18: ai.AIService.Embed:output_type -> ai.EmbedResponse
	18, // 19: ai.AIService.ChatAnswer:output_type -> ai.ChatChunk
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ai_ai_service_proto_init() }
func file_proto_ai_ai_service_proto_init() {
	if File_proto_ai_ai_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_ai_service_proto_rawDesc), len(file_proto_ai_ai_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_ai_service_proto_goTypes,
		DependencyIndexes: file_proto_ai_ai_service_proto_depIdxs,
		MessageInfos:      file_proto_ai_ai_service_proto_msgTypes,
	}.Build()
	File_proto_ai_ai_service_proto = out.File
	file_proto_ai_ai_service_proto_goTypes = nil
	file_proto_ai_ai_service_proto_depIdxs = nil
}
