[project]
name = "ai-service"
version = "0.1.0"
description = ""
authors = [
    {name = "Kunal Pisolkar",email = "55585892+kunalPisolkar24@users.noreply.github.com"}
]
requires-python = ">=3.12"
dependencies = [
    "grpcio (>=1.83.0,<2.0.0)",
    "grpcio-tools (>=1.83.0,<2.0.0)",
    "grpcio-health-checking (>=1.83.0,<2.0.0)",
    "pydantic-settings (>=2.14.2,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-asyncio (>=1.4.0,<2.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "ruff (>=0.16.1,<0.17.0)"
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
pythonpath = ["."]

[tool.ruff]
exclude = ["src/generated"]

[tool.coverage.run]
omit = ["src/generated/*"]
